### ISSUE TITLE
Failure to load imzML with units "number of detector counts"

### ISSUE THREAD

**Issue by AlanRace** [prafols/rMSI#1]
The name for the unit 'MS:1000131' in the mzML ontology is "number of detector counts" (https://raw.githubusercontent.com/HUPO-PSI/psi-ms-CV/master/psi-ms.obo), however rMSI fails to load imzML files which use this exact text as it expects "number of counts". Error included below.

 Error in .controlled_loadAbort("intensity Arrays are not in number of counts units, rMSI does not support it\n",  : 
  intensity Arrays are not in number of counts units, rMSI does not support it

**Comment by prafols** [comment]
This has been fixed on commit 97bcc427965fc86353dca19e5d19d8234d560c1e. It will be available on next release 0.7.
