### ISSUE TITLE
loadImgChunk from Ids and Coord doesnt work for me.

### ISSUE THREAD

**Issue by victoriavoss96** [prafols/rMSI#3]
### Error:
<pre><code>
mySpectra <- rMSI::loadImgChunkFromIds(myData, c(101, 142, 230))
Error in data.frame(id = Ids, cube = icube, row = irow) : 
  arguments imply differing number of rows: 3, 0
</code></pre>

### Description 
This error persists when i try to follow the quickstart guide. 
The Ids exists. The Data used is the example data provided. 
Same error happens for Coord loading. 
My System is Manjaro Linux, everything is up to date

**Comment by victoriavoss96** [comment]
Nevermind it was a case of user to stupid(me), 
I loaded the data with OpenMSI() so the correct Identifier for myData was myData$img1

**Comment by prafols** [comment]
I'm glad you solve it. Apologizes for my late response I've been busy and not able to reproduce your issue.
