### ISSUE TITLE
package ‘RGtk2’ is not available for this version of R

### ISSUE THREAD

**Issue by QQhuan** [prafols/rMSI#9]
When I install "RGtk2", I got errors as follows: 
```
Warning in install.packages :
  package ‘RGtk2’ is not available for this version of R

A version of this package for your version of R might be available elsewhere,
see the ideas at
https://cran.r-project.org/doc/manuals/r-patched/R-admin.html#Installing-packages
```
> env: R 4.4.0; Rtool 4.4; window11;

**Comment by prafols** [comment]
Hi, rMSI is outdated. Please, check out rMSI2 which includes all the processing from an rMSIproc and some major improvements, and also solves this issue:  https://github.com/prafols/rMSI2
